apiVersion: v1
kind: Pod
metadata:
  labels:
    app: employeesapp
  name: app-pod
  namespace:  webapplication
spec:
  containers:
  - name: employeesapp
    image: 232901375965.dkr.ecr.us-east-1.amazonaws.com/asn2:appv1.0
    ports: 
    - containerPort: 8080
      protocol: TCP
    env:
    - name: DBHOST
      value : "10.244.0.3"
    - name: DBUSER
      value : "root"
    - name: DBPWD
      value : "vishal"
    - name: DBPORT
      value : "3306"
