apiVersion: v1
kind: Service
metadata:
  name: appservice
  labels:
    app: employ
  namespace: webapplication
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employees
